### ISSUE TITLE
How to use in windows?

### ISSUE THREAD

**Issue by tiam-bloom** [bensadeh/tailspin#103]
I use `tspin -f  2023-12-30.log` command, and prompt "'less' command not found. Please ensure it is installed and on your PATH."
what should I do?

**Comment by ldubos** [comment]
if you have installed git with `scoop` on windows you can simply add `C:\Users\<username>\scoop\apps\git\current\usr\bin` to your path it works for me

**Comment by tiam-bloom** [comment]
> if you have installed git with `scoop` on windows you can simply add `C:\Users\<username>\scoop\apps\git\current\usr\bin` to your path it works for me

Thanks, I find  installed git path add in system environment and it works, but my path `F:\Program\Git\usr\bin` is different  from you, I looks here have `less.exe` file in that path, I guess is it works .
Hope you can understand my mean(my English is very bad) . Anyway, thank you very much.

**Comment by bensadeh** [comment]
Hi @tiam-bloom , thanks for opening this ticket and thanks to @ldubos for helping out with troubleshooting.

Unfortunately, I don't use Windows so it's difficult for me to provide useful advice other than saying that the error message is descriptive in the sense that `tailspin` depends on `less` at the time of writing.

In the meantime, see https://github.com/bensadeh/tailspin/pull/100 for efforts to try using `minus` as the pager, which would be built-in and not an external dependency.
