### ISSUE TITLE
Add Alpine Linux

### ISSUE THREAD

**Issue by yonas** [bensadeh/tailspin#113]
Would be nice to see this package in the Alpine package repo.

**Comment by bensadeh** [comment]
That would be great! Would be happy to look at a PR if anything needs be done on this side.

**Comment by yonas** [comment]
Created https://gitlab.alpinelinux.org/alpine/aports/-/issues/15730 . I'll update here when it's been added.

**Comment by yonas** [comment]
Congrats! Tailspin has been added to the testing repository.

**Comment by bensadeh** [comment]
Amazing 🤩, thanks to everyone for helping put tailspin on Alpine Linux 🙏
