### ISSUE TITLE
Color blue is too dark to be readable on a black background

### ISSUE THREAD

**Issue by thomas-maeder** [bensadeh/tailspin#136]
It looks as if tailspin could be a very useful tool.

Unfortunately, the promise `No setup or config required` is not quite true. At last the colors would have to be chosen so that they are readable on the background of the terminal where tailspin is used.

Can I configure my own RGB codes for the colors?
The documented set of color names is very small - are there others?

**Comment by bensadeh** [comment]
Hi @thomas-maeder and thanks for trying out `tailspin`.

In simple terms, `tailspin` does not chose which colors are drawn to the screen. Instead, it sends a "signal" that certain pieces of text should be rendered in red/blue/green etc. to the terminal. 

It is therefore terminal emulator which decides what color it should end up with. This is how terminal color schemes are made. 

If the colors don't look good in your terminal, I suggest switching color scheme. It is the responsibility of the color scheme to make sure the default colors look good together.  

In the screenshots I am using [`palenight`](https://github.com/JonathanSpeek/palenight-iterm2). Other popular themes are [`catppuccin`](https://github.com/catppuccin/iterm).
