### ISSUE TITLE
Question about DD/MM/YYYY date format highlighting

### ISSUE THREAD

**Issue by benwebbbenwebb** [bensadeh/tailspin#159]
Hi team

Love the work.

Wondering if dates formatted DD/MM/YYYY (and date time strings DD/MM/YYYY, HH:MM:SS a) are expected to work out of the box?

I could definitely be doing something wrong, but currently they aren't highlighting how I'm expecting...

![log_highlighting](https://github.com/user-attachments/assets/110ba50d-82aa-4191-ba7a-3e9bb13e31a8)

**Comment by bensadeh** [comment]
Hi @benwebbbenwebb and thanks for trying out `tailspin`! (Although there is no team, just me 😎 )

Glad you're finding the tool useful.

This format should be supported for sure. I am currently working on some larger refactoring of `tailspin` but I hope that a fix for this can be out in the next release.

**Comment by inianv** [comment]
@bensadeh love your work on this and it has replaced my usage of `stern` for the last few months. Would love to contribute to the tool.

**Comment by bensadeh** [comment]
Fixed in #172
