### ISSUE TITLE
Highlight errors when the string contains escaped quotes

### ISSUE THREAD

**Issue by kenchou** [bensadeh/tailspin#171]
reproduct:

```
echo '{"info": "{\"int\":3,\"string\":\"test\",\"bool\":false}"}' | tspin
```

**Comment by bensadeh** [comment]
Hi @kenchou and thanks for opening this issue with a clear example to reproduce.

In short, escape symbols are for the machine, while tailspin reads logs that are readable by humans. Handling escape symbols in outside of the scope of this tool.
