### ISSUE TITLE
assumes less is configured to interpret ANSI escape codes

### ISSUE THREAD

**Issue by jonassmedegaard** [bensadeh/tailspin#22]
On my Debian system, running tailspin on a logfile warns that output "may be a binary file", and if I accept to see it anyway it shows the logfile with lots of escape codes where coloring was expected.

If I instead run tailspin with environment variable LESS="R" then it displays colors as expected.

I suspect your test environment is configured to have less parse escape sequences, which is *not* the default behaviour of less, as far as I can see in the less decoumentation.

I guess the proper thing to do is to add option -R to lines 7 and 9 of src/less/mod.rs, to ensure that ANSI escape code parsing is enabled regardless of environment setup.

**Comment by bensadeh** [comment]
Hi again! 

Good catch! Yes, we should definitely run `less` with the `--RAW-CONTROL-CHARS` flag by default. Will include this in the next release.

**Comment by bensadeh** [comment]
Fixed in `1.1.0`.
