### ISSUE TITLE
less is passed path as a regular option

### ISSUE THREAD

**Issue by jonassmedegaard** [bensadeh/tailspin#23]
It is safer to tell less that the path must *not* be accidentally parsed as an option, by using "--" as delimiter.

I.e. instead of "less +F somefile" it is safer to call it as "less +F -- somefile".

**Comment by bensadeh** [comment]
Thanks for the suggestion! I didn't know about the way to specify the path with `--`. Will include in next release.

**Comment by bensadeh** [comment]
Fixed in `1.1.0`.
