### ISSUE TITLE
generate-config writes to hardcoded path

### ISSUE THREAD

**Issue by jonassmedegaard** [bensadeh/tailspin#26]
I think it would be better if subcommand `generate-config` would not create default config file, but simply spew config data to stdout.  That way, the user is free to either create default or custom config file, or to use the output to make a diff against an existing config file.

Additionally, I think it would be better if a) instead of a hardcoded default path XDG evironment variables was consulted (which leads to same default path as now, so no surprises for the millions of existing users of the tool), and b) not only a user-specific path is used but (when that is missing) system-shared paths are consulted too.
All of this seems possible with the crate `microxdg` using `Xdg::search_config_file()`.
(the more popular crate `Directories` unfortunately [does not support system-wide lookups](https://github.com/dirs-dev/directories-rs/issues/82)).

**Comment by bensadeh** [comment]
Thanks for posting this issue. XDG support is planned and coming.

To accommodate for more options for the config, the config command will take arguments and look something like this in the future:

```console
spin config --generate
spin config --print-default
```

**Comment by bensadeh** [comment]
In `1.2.0` there are now two flags that more explicitly state what is happening:

```console
--create-default-config  Generate a new configuration file
--show-default-config    Print the default configuration 
```

Moreover, if `XDG_CONFIG_HOME` is set, it will be used for both creating and reading from config.
