### ISSUE TITLE
Simple output (i.e. no call to `less`)

### ISSUE THREAD

**Issue by Glandos** [bensadeh/tailspin#30]
This is an incredible valuable project, thanks!

But to be honest, sometimes, I much prefer the behavior of a simple `tail -f`, where I can "put" separator by hitting `Enter` key.
Is it possible to add a mode where `tailspin` or `tailspin -f` completely skip the `less` part?

**Comment by bensadeh** [comment]
Hi @Glandos !

Glad you enjoy tailspin!

Help me understand your question a bit more 😄 . Would you like tailspin to output the contents directly to stdout like what for example `cat` does?

**Comment by Glandos** [comment]
Exactly.
Of course, since it is a **formatter**, special characters should be printed, so that a terminal will show those formatting (color/italic/…).

The goal is to be able to use some terminal feature like scroll buffer for long logs.

**Comment by bensadeh** [comment]
Great! Happy to add the functionality 😎 .

Expect to see it in the next release. I'll update the ticket when it is ready.

**Comment by bensadeh** [comment]
Added `-p` / `--print` flag in 750f314b14556a0f1dda7b06641a064151382029. Will close the ticket when `1.2.0` is released.

**Comment by bensadeh** [comment]
Just released `1.2.0`, hope it works like you expect!
