### ISSUE TITLE
needless build-dependency on clap_mangen

### ISSUE THREAD

**Issue by jonassmedegaard** [bensadeh/tailspin#32]
Manifest declares an unused build-dependency on clap_mangen (should have been drop when reverting to generating with asciidoc).

**Comment by bensadeh** [comment]
Yes, you are right, I forgot to remove this dependency on the revert. May I ask you how you found out? Is there a tool or something that can report on this to make it easier to spot unused deps?

**Comment by jonassmedegaard** [comment]
What lead me to notice the added dependency was that Debian packaging is done in a clean-room environment where each and every dependency needs to be declared explicitly (in Debian packaging metadata - the Cargo.toml manifest is not consulted for that).

What lead me to notice that the added dependency was unneeded was that ideally a Debian package is built purely from source, so instead of simply installing your pre-generated manpage and shell completion scripts, I repeated your routines to generate those as part of the Debian build, where I then struggled with the "man" action until I noticed that you had rolled that part back again.

**Comment by bensadeh** [comment]
Ah, yes, I see now. Interesting how Debian packaging works, thanks for explaining. The clap_mangen dependency has now been removed.
