### ISSUE TITLE
apt: `Unable to locate package tailspin`

### ISSUE THREAD

**Issue by bensadeh** [bensadeh/tailspin#53]
Some users are reporting errors when installing using `apt`: https://news.ycombinator.com/item?id=38111874.

Looking for help troubleshooting as I don't use a Debian based system.

**Comment by wu-yue-yu** [comment]
I got this error too, I guess there's no prebuilt package uploaded to the software source.
My workaround is installing from source.
My system is Ubuntu 22.04.

**Comment by bensadeh** [comment]
I think I need to close this issue as am not involved in packaging `tailspin` and there isn't anything I can do. 

Feel free to reopen if there is anything I can do on my side.
