### ISSUE TITLE
Add homebrew package

### ISSUE THREAD

**Issue by qa-alexander-eimer** [bensadeh/tailspin#54]
It would be lovely to have a homebrew-core package to just run: `brew install tailspin`.

Alternatively a tailpsin tap would be a nice solution, then a `bensadeh/homebrew-tap` repo is needed and to install would need:

```bash
brew tap bensadeh/tap
brew install tailspin
```

**Comment by LaurentFough** [comment]
I've created a Homebrew package formula... tested & installed.
Will submit a PR.
—-
Will also tweak formula for increased Homebrew compliance.

**Comment by bensadeh** [comment]
Thank you so much, @LaurentFough ! Can't believe how fast that was 🙏 .

It would be great if the package name could be `tailspin` and the binary name be `spin`. Is that possible?

**Comment by LaurentFough** [comment]
Update: temp Formula here: [github.com/LaurentFough/ Tailspin.rb](https://github.com/LaurentFough/tailspin/blob/main/Tailspin.rb)

Download & Review (of course), then Install with:
> `$ brew install --formula <path_to>/Tailspin.rb`

**Comment by LaurentFough** [comment]
> Thank you so much, @LaurentFough ! Can't believe how fast that was 🙏 .
> 
> It would be great if the package name could be `tailspin` and the binary name be `spin`. Is that possible?

Thanks @bensadeh 
Ok - package is already named: tailspin.
See my previous comment about the conflicting `spin` package.
—-
Would be cleaner for you to rename upstream as `tailspin`; rather than installing as `spin` and renaming...

**Comment by bensadeh** [comment]
I prefer `spin` as the binary name. Besides, `tailspin` is already a binary on macOS.

**Comment by LaurentFough** [comment]
> I prefer `spin` as the binary name. Besides, `tailspin` is already a sort of builtin binary on macOS.

ok, then as is... the current formula will install and work as expected, and will warn/notify the user if they already have the _other_ `spin` installed.

**Comment by bensadeh** [comment]
Thanks again @LaurentFough , really appreciate how quickly you managed to put this together 🙏

**Comment by LaurentFough** [comment]
> Thanks again @LaurentFough , really appreciate how quickly you managed to put this together 🙏

I wanted to test on macOS, so no worries & You're welcome.

**Comment by LaurentFough** [comment]
+ Added Homebrew/tap installation instructions as well.

**Comment by bensadeh** [comment]
Thank you again @LaurentFough . Merged in #56 .

**Comment by qa-alexander-eimer** [comment]
Honestly, I don't think this how homebrews tap system is meant to work. My suggestions were completely ignored. Also is there any automation for a version bump/update?

**Comment by bensadeh** [comment]
[A PR to add tailspin as formula to core has been merged](https://github.com/Homebrew/homebrew-core/pull/153186). I haven't had a chance to test it, but in time the tap will be replaced with the core formula.

**Comment by qa-alexander-eimer** [comment]
Oh neat!

```bash
brew uninstall tailspin
brew untap bensadeh/tailspin
brew update
brew install tailspin
```

works!

**Comment by bensadeh** [comment]
Great, I will update the readme with the changes. Thanks for helping with the tap in the meantime @LaurentFough . Sorry your tap couldn't be used more, but it is easier for me to let the formula from core be maintained and updated there.

**Comment by LaurentFough** [comment]
> Honestly, I don't think this how homebrews tap system is meant to work. My suggestions were completely ignored. Also is there any automation for a version bump/update?

@qa-alexander-eimer That actually is how taps are supposed to work.
For 3rd-Party taps, anyway - the only missing ingredient was the provision of a `homebrew-tailspin` repo.
Everything else was compliant with Homebrew recommendations.

@bensadeh No worries; I prefer the submission to Homebrew-core as well.

If you're going to create an automation for release updates, let me know.
