### ISSUE TITLE
Binary name conflict

### ISSUE THREAD

**Issue by 0323pin** [bensadeh/tailspin#57]
Hi,

I was asked to package `tailspin` for pkgsrc/NetBSD yesterday.
I'll be working on getting this done in an hour or so, but I've noticed that renaming the binary and `sed`ing the new name into the manpage will be required, as there's already a `spin` binary in the package tree.

Considering the existence of [spin](https://github.com/nimble-code/Spin), it would probably be better to call the binary `tailspin` and avoid conflicts.

I'm open to other suggestions if you have other preferences.

Regards

**Comment by bensadeh** [comment]
Hi @0323pin and thanks for looking into packaging `tailspin` for pkgsrc/NetBSD.

Ah, this seems to be a reoccurring issue in packaging `tailspin`, see #21 and #54 for example.

If possible, I like the binary names to be short as I feel it adds to the simplicity of the tool itself. However, I am open to suggestions as well if there are practical reasons for doing it another way.

One issue with renaming the binary to `tailspin`, is that macOS comes with a binary that is also called `tailspin`, and I am not sure what the implication of shadowing binaries in that way will be.

I am not familiar with the packaging process for pkgsrc/NetBSD. What are some of the options moving forward?

**Comment by 0323pin** [comment]
Ahh ...

> One issue with renaming the binary to tailspin, is that macOS comes with a binary that is also called tailspin,

This is not good. pkgsrc support macOS also and renaming to `tailspin` would cause a conflict on macOS.
What about `tspin` or, `tsp`? The package itself will still be called `tailspin`, though.

**Comment by bensadeh** [comment]
I am leaning towards `ts`, as it is reminiscent of `ripgrep` --> `rg` as the binary name. But I want to make sure that is not conflicting with any other binaries first. Do you know of a good way to check binary names across different package managers?

**Comment by 0323pin** [comment]
> I am leaning towards ts ...

😞 http://vicerveza.homeunix.net/~viric/soft/ts/

> Do you know of a good way to check binary names across different package managers?

Not really but, I can easily check pkgsrc for you.

**Comment by bensadeh** [comment]
No problem, thanks for looking it up. 

`tspin` looks to be the simplest and most unique binary name so far. I want to make sure this binary doesn't have any other conflicts, but if it doesn't we can perhaps settle on that as the binary name.

**Comment by 0323pin** [comment]
@bensadeh I've run `grep -r "tspin" pkgsrc/` (this includes the whole package tree) an got **no** hits for `tspin` 😃

**Comment by bensadeh** [comment]
Great! 😄 

If there are no issues with this elsewhere, I'll update the binary name for the upcoming `1.7.0` release. Thanks again for reaching out.

**Comment by 0323pin** [comment]
You could check [repology](https://repology.org/).

I have a package ready to be merged now. It will be in the main tree in a few minutes.

**Comment by 0323pin** [comment]
Merged, http://mail-index.netbsd.org/pkgsrc-changes/2023/11/03/msg285784.html

**Comment by bensadeh** [comment]
Thanks for taking the time to put this together, really appreciate it. 🙏

**Comment by 0323pin** [comment]
There's a PR now, to add install instructions to the README file 😉
