### ISSUE TITLE
How to disable the builtin keywords (Booleans, Severity Levels, REST etc.)

### ISSUE THREAD

**Issue by kmoppel** [bensadeh/tailspin#60]
The defaults are pretty good but would like to disable highlighting of "true" and "false" - how to best achieve that? The examples don't seem to mention booleans. Thanks!

**Comment by bensadeh** [comment]
Hi @kmoppel ! 

Thanks for trying out `tailspin`.

The configuring of all the highlight groups was recently reworked, and I forgot to include a way to disable all the highlights which were based on keywords (including booleans, log levels, REST verbs etc.).

There will be a way to disable these in the upcoming release `2.1.0`.

**Comment by bensadeh** [comment]
Just released `2.1.0` which allows you to disable the custom keyword highlighting.
