### ISSUE TITLE
How to use with vscode

### ISSUE THREAD

**Issue by abulka** [bensadeh/tailspin#65]
Since many developers use vscode and vscode outputs log information to the `debug console` or `terminal output` panel, it would be good to be able to pipe that log into through `tailspin`. 

Any idea how to achive this? Perhaps some clever vscode launch config?

e.g.
<img width="1111" alt="image" src="https://github.com/bensadeh/tailspin/assets/11467530/ac790b56-1d25-4891-bb02-156602367a0c">

**Comment by bensadeh** [comment]
That would be very cool. I was looking into if something similar was possible in IntelliJ or the other JetBrains IDEs, and so far I do not how to integrate the tool with them. If someone finds a way, I am happy to update the readme.

**Comment by bensadeh** [comment]
I think I am going to close this issue since I don't actually know how to use tailspin with vscode or intellij for that matter. Feel free to reopen if there is progress here and I will update the readme with instructions on how to integrate it with the IDEs.
