### ISSUE TITLE
Support more keywords

### ISSUE THREAD

**Issue by yanxiang-wang** [bensadeh/tailspin#68]
Here are some logging definitions from `loguru` in Python.

Level name | Severity value | Logger method
-- | -- | --
TRACE | 5 | logger.trace()
DEBUG | 10 | logger.debug()
INFO | 20 | logger.info()
SUCCESS | 25 | logger.success()
WARNING | 30 | logger.warning()
ERROR | 40 | logger.error()
CRITICAL | 50 | logger.critical()

**Comment by bensadeh** [comment]
Thanks for letting me know. Added some more builtin keywords in ecdf9f82f45dcc131f599e46a84c5dd4dedc0499.
