### ISSUE TITLE
Recognize and parse JSON and logfmt

### ISSUE THREAD

**Issue by alexec** [bensadeh/tailspin#7]
If the input is in these two formats, parse them to canonical format.

**Comment by bensadeh** [comment]
Thanks for pointing me to logfmt, I wasn't aware this was somewhat of a standard.

Can you say a bit more on the use case for this, or in other words, what kind of logs are not highlighted in the way you expect?

`tailspin` is meant to be used on many different log formats with little to no configuration. Contrast this to other log highlighters that can be more specific (`lnav`, specific JSON highlighters etc.). They can offer better log highlighting than `tailspin`, but they may require more setup upfront.

If you can provide me with some example logs and how you expect them to be highlighted, it might be easier to move forward with improving the highlighting of `tailspin`. I realize not everything I wrote here is documented, so this was a good reminder to update the readme.

**Comment by alexec** [comment]
I think you’re probably right here. One thing I like is only showing ERROR logs. These can be found by lines that contain “ERROR” in them.

**Comment by bensadeh** [comment]
Hi again @alexec ,

The readme now shows how to filter lines with error in them. It also contains a section in the introduction about the behavior of tailspin in reading line-by-line and applying regexes to them.

Will close the issue, but feel free to reopen or post a new ticket if needed.
