### ISSUE TITLE
Automatically open compressed log files

### ISSUE THREAD

**Issue by retrodaredevil** [bensadeh/tailspin#71]
I have a feature request that would benefit my workflow.

I have a directory with a bunch of compressed log files in them, so I end up doing something like this:

```shell
gunzip some_info.log.gz
tspin some_info.log
```

It would be nice if there was an option to automatically decompress the file and store it in the same location without the `.gz` extension, or in the case of a small file, just decompress it in memory so no extra file is created.

Not sure if this is something you would want to implement, but it would make viewing log files easier for me.

**Comment by bensadeh** [comment]
Hi @retrodaredevil and thanks for opening this issue.

Unfortunately, I think this is a bit out of the scope of what I envision `tailspin` to be. This is a hobby project for me, so my time to work on it is limited.

However, I do believe that you could create a small shell script to temporarily decompress and then clean up the files afterwards, if I understood your feature request correctly. I appreciate you taking the time to open the issue anyway.

**Comment by retrodaredevil** [comment]
Thanks for the response. Yeah I totally get not wanting to implement this feature. Takes some of the simplicity out of what this is. 

I probably will create my own script.

**Comment by bensadeh** [comment]
Feel free to drop by and share if you ended up with a cool script. If it is useful, we can think about updating the readme with a "tips and tricks" section.
