### ISSUE TITLE
Better error message when `less` binary not found

### ISSUE THREAD

**Issue by retrodaredevil** [bensadeh/tailspin#72]
I recently ran `tspin` on a system without `less` installed, and I got this error:

```console
lavender@pi:~$ tspin -f /opt/my/path/log_info.log
Failed to run less: No such file or directory (os error 2)
The application panicked (crashed).
Message:  called `Result::unwrap()` on an `Err` value: Custom { kind: Other, error: "background task failed" }
Location: /home/lavender/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tailspin-2.0.0/src/main.rs:59

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets
```

I think having a nicer error message would really help people understand what they need to do (install less) in order to get it working.

**Comment by bensadeh** [comment]
Hi again @retrodaredevil , and thanks for letting me know about this.

Yes, I totally agree, we could do with a better error messages in these cases. I think I just assumed every system would have `less` installed.

Out of curiosity, what system are you using that does not come with `less` installed?

**Comment by retrodaredevil** [comment]
I had a DietPi install, so it was pretty minimal.

**Comment by bensadeh** [comment]
Added better error messages in a5454805404578f854313d255271296ac50b25c1.
