### ISSUE TITLE
Statically-linked binaries on GitHub Release

### ISSUE THREAD

**Issue by ecarrara** [bensadeh/tailspin#74]
Consider adding statically-linked binaries for Mac OS X, Linux, and OpenBSD. This would make it super convenient for users to download and use the executable via HTTPS, quickly and securely.

**Comment by supleed2** [comment]
To add to this, binaries that can be installed via [`cargo binstall`](https://github.com/cargo-bins/cargo-binstall), or similar, would be much appreciated.
