### ISSUE TITLE
IPv6 support for IP adresses

### ISSUE THREAD

**Issue by Glandos** [bensadeh/tailspin#76]
For now, only IPv4 [dot-decimal notation](https://en.wikipedia.org/wiki/Dot-decimal_notation) is supported.

It could be good to support IPv6 hexadecimal notation.

**Comment by bensadeh** [comment]
Hi again @Glandos ! 

Yes, totally agree. IPv6 should definitely be added as well.

**Comment by bensadeh** [comment]
Added in `3.0.0` 🎉
