### ISSUE TITLE
just a suggestion regarding another cool utility I've come across...

### ISSUE THREAD

**Issue by mikeggh** [bensadeh/tailspin#77]
Recently I came across spacer, and it is the first time I've considered changing my approach to console based tailing..
https://github.com/samwho/spacer

This would be a really cool feature to have with tailspin!  I may admit though, I think tailspin has won me over already...

keep up good work!

**Comment by bensadeh** [comment]
Hi @mikeggh and thanks for opening this issue. I'm glad you like `tailspin` so far.

One of my goals with `tailspin` is to create a tool that is easy to integrate with other command line tools, like `spacer` for example.

Although not possible today, ideally you would be able to run:

```console
tspin --follow --print some.log | spacer --after 5
# instead of 
tail -f some.log | spacer --after 5
```

I believe this will be possible when https://github.com/bensadeh/tailspin/issues/75 is fixed.

**Comment by mikeggh** [comment]
Sounds good.. looking forward to all updates!  I've already incorporated it into my arsenal.. =]
have a good weekend

**Comment by mikeggh** [comment]
I had decided to take a dive to see if I could add some timing/statistics to "Waiting for data."  I had never used less +F, and had no idea it was where the message was coming from.  It makes a lot more sense now that I've tracked things down, and understand why for the time being it is pretty static.  I had even checked if it would be easy to LD_PRELOAD it for my own usage, and it just doesn't seem worth it when able to use spacer as you stated. =]

**Comment by bensadeh** [comment]
I did some testing and you can already use `tailspin` for highlighting in combination with other tools, like `spacer`.

For example, in combination with `tail` and `spacer` you could do this:

```console
tail -f some.log | tspin | spacer --after 5
```

Is this what you were thinking about?

**Comment by mikeggh** [comment]
Yeah,  That works for now!  It was my initial train of thought, and then I wanted to add some extra information to the "Waiting for data" line.  I was considering "Waiting for data for 10 seconds," or "10 lines per minute."  It works till one day I wanna modify less, or finally bite the bullet and try my hand at rust. :)

**Comment by bensadeh** [comment]
Great! Thanks for the feedback, glad you're enjoying using tailspin 😄 .
