### ISSUE TITLE
Not getting colorized/formatted output with follow

### ISSUE THREAD

**Issue by bd-g** [bensadeh/tailspin#81]
With both the `-f` and `-l` flags on the v2.0.0 release, The output is just printed plain to the screen, no formatting.

**Comment by bensadeh** [comment]
Hi, I am not able to recreate this. Can you provide a minimal reproducible example?

**Comment by bd-g** [comment]
I figured it out - the process I was piping to `tspin` was outputting to `stderr`, and `tspin` is only going to operate on output from `stdout` (which is correct Unix behavior). Thanks for the response, I'll close the issue!

**Comment by bensadeh** [comment]
Thanks for updating the ticket! Glad you got it working in the end 😄
