### ISSUE TITLE
Support for highlighting pointers

### ISSUE THREAD

**Issue by agnosticlines** [bensadeh/tailspin#91]
Hey! I love this tool! One thing that would be really useful for low level developers is highlighting pointers/memory addresses, potentially also splitting them up into 32bit chunks so they're easier to read :)

**Comment by bensadeh** [comment]
Hi @agnosticlines ! Glad you like `tailspin`!

Yes, I agree that this is something useful to highlight. I have some ideas on how to do it, I just want to make sure it turns out well.

**Comment by bensadeh** [comment]
Added in `3.0.0` 🎉
